# Generated by Django 2.1.1 on 2018-09-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0002_auto_20180928_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='path',
            new_name='image',
        ),
    ]
